### ISSUE TITLE
Feature Request: Change Volume

### ISSUE THREAD

**Issue by glenndehaan** [onetune/spotify-web-helper#31]
Is it possible to control the volume through this API. If so can you implement it?

**Comment by itotallyrock** [comment]
Using the SpotifyWebHelper itself I believe this is not possible because Spotify uses their own WebSockets to control volume.  The only potential implementation would be through triggering keypresses to the system, but this is outside the scope of this application.  If you want this feature I suggest you check out [node-media-controller](https://www.npmjs.com/package/node-media-controller) for windows, [AppleScript commands](https://www.npmjs.com/package/spotify-node-applescript) for OS X, and if you only care about volume [Loudness](https://www.npmjs.com/package/loudness) for linux.  However, if I'm mistaken and somehow you can implement it within the WebHelper or even the WebSocket feel free to either post here or create a pull request.

**Comment by JonnyBurger** [comment]
This repository is an interface for the Spotify Web Helper API, which does not support volume.
However, it seems to be possible using the new Web API endpoints (you need to authenticate the user for this though): https://developer.spotify.com/web-api/set-volume-for-users-playback/
