### ISSUE TITLE
No longer plays artist uri

### ISSUE THREAD

**Issue by nikshriv** [onetune/spotify-web-helper#33]
Artist uri playback suddenly stopped working a couple of weeks ago. I suspect this is due to a recent app update. tracks and albums still work.

**Comment by itotallyrock** [comment]
Forgive me if I'm misinterpreting this, but you're saying that you cant play a URI for an artist, but it still works with other URIs?

I've never tried playing an artist URI directly so I don't know the expected behavior, I imagine it will just play their popular songs like in the application.  Perhaps there is a work around to get the playlist for an artists popular songs?

**Comment by nikshriv** [comment]
Sorry, I tried testing it today. Im unable to play anything at this point. I'm getting this error:

ECONNREFUSED 127.0.0.1:4370

It looks like it won't connect to webhelper anymore. It used to work perfectly. Thanks for looking into it



________________________________

**Comment by itotallyrock** [comment]
I've tested a new an instance on my system and it worked as expected, so it is likely an issue with the environment your instance is running in.  If you're running it along with any dependencies you may want to check those, give some system information like OS, Spotify version, etc.

You could also test with just using the WebHelper without using this API [over HTTP](http://cgbystrom.com/articles/deconstructing-spotifys-builtin-http-server/) to narrow it down to the scope of this package versus an issue with Spotify or your system.

As for the original issue of not being able to play artist URI's that may need some looking into if Spotify changed their end regarding those.
