### ISSUE TITLE
503 Error Using Windows 10 While Retrieving Status

### ISSUE THREAD

**Issue by mwalden2004** [onetune/spotify-web-helper#37]
I'm getting
```
node:26988) UnhandledPromiseRejectionWarning: HTTPError: Response code 503 (Service Unavailable)
    at stream.catch.then.data (D:\Projects\DesktopBackground\node_modules\got\index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

and my code is

```javascript
const SpotifyWebHelper = require('spotify-web-helper');

const helper = SpotifyWebHelper();
helper.player.on('ready', () => {
  console.log(helper.status);
  // 'status': {
  //    'track': ...,
  //    'shuffle': ...,
  //    'playing_position': ...
  //  }

});
```

**Comment by itotallyrock** [comment]
Hello, thank you for submitting your issue.  I'm unable to reproduce this issue myself, I think this might just be an issue with [Spotify on your end](https://community.spotify.com/t5/Accounts/503-Service-Unavailable/td-p/1651683).  If you think this is an issue with this repository, more information will likely be needed: if your spotify is up to date, if you can access Spotify through your browser, or if none of those work restarting your computer/network that could be interfering.  Regardless, we could use handling the promise and emitting an error instead of the letting it go uncaught.

**Comment by mwalden2004** [comment]
I was trying to find what the issue was, and I have found out it's Electron not compiling correctly, Thank you, and sorry to waste your time.

**Comment by mwalden2004** [comment]
Apparently I can't close the issue, can you?
