### ISSUE TITLE
Events firing before status object is updated

### ISSUE THREAD

**Issue by TimStallard** [onetune/spotify-web-helper#8]
I'm attempting to use this project to provide a live view of the current song and status, which I'm reading from the status object. However, I'm firing my change code from the play, pause, end and track-change events, and when my event handler is executed, the status object is not updated.

Looking over the code, it appears that the compareStatus function, which emits the relevant events, is executed before the new status is saved.
For now, I've just added a new event that fires after line 328, which works for my situation but does not resolve the main issue. I guess a fairly simple solution would be to save the current state and also update the main state object, and then pass the old state to the compareStatus function for comparison, which would then fire the events. If you think this would be a reasonable solution, I'd be happy to submit a PR.

**Comment by JonnyBurger** [comment]
I have pushed a version 1.4.0 that renames the event from `track-change` to `track-will-change`.
The event name suggested that the status is immediately updated which is not true.
The old event name still works but is deprecated.

I have decided against updating the state before calling the event for multiple reasons. First, you can read the new track directly from the event:

``` js
helper.player.on('track-will-change', track => {
    console.log('the new track is', track);
});
```

There is no need to monkeypatch the library.

Secondly, it allows for the possibility to manually compare against the old state, which seems potentially useful.
Thirdly, the change could potentially break existing applications and I don't want to push `v2.0.0` because of this, since it hurts adoption.
Lastly, the code of the library would become more complex because the old state needs to be held somewhere after it was already updated.

I hope you agree that this makes sense!

**Comment by TimStallard** [comment]
Thanks for your reply - that makes much more sense now.

In addition to the current events, it might also be nice to have a generic "status-will-change" event, which passes the entire new status object. This would be a very simple addition, and would make it much easier to write events dealing with the entire status object.
I think that this might be a much nicer solution than the one I proposed earlier, since it wouldn't make any breaking changes, and also doesn't require any additional storage of state. However, I see that this may cause some issues with time updates, since I don't know if the event should be fired as the time changes or not. I'd appreciate hearing your thoughts on this.

**Comment by JonnyBurger** [comment]
I would be ok with this. This sounds like an easier way to update the whole UI, you only need one event.
For that reason I think it's also ok if that event fires when only the time is updated.

Because I don't need this in my projects at the moment, I'm not implementing it in the foreseeable future.
But I would accept a PR.
